
server:
  port: 7070
 
  servlet:
    context-path: /xdiamond-spring-boot
 
spring:
  profiles:
    active: dev

#  redis:  
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password: 
#    timeout: 6000ms
#    jedis:
#      pool:
#        max-active: 1000
#        max-wait: 100000
#        max-idle: 10
#        min-idle: 5

  autoconfigure:
    exclude:
    - 

  http:
    log-request-details: true

# spring.devtools.restart.enabled 禁用devtools自动重启功能，直接用IDE的热部署
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java


xdiamond: 
  serverHost: 192.168.5.11









